language: ruby
sudo: false
dist: xenial
services:
- redis-server
- xvfb
cache:
- bundler
bundler_args: "--without staging,production"
addons:
  postgresql: "9.6"
  chrome: "stable"
  apt:
    sources:
      - kalakris-cmake
      - google-chrome
    packages:
      - cmake
      - google-chrome-stable
      - chromium-chromedriver
before_install:
- nvm install --lts
- npm install -g yarn
- ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
before_script:
- cp config/database.travis.yml config/database.yml
- cp .env.example .env
- bin/yarn install
script:
- bundle exec rake db:setup webpacker:compile spec
notifications:
  email: false
